export interface Ability {
    "Version": number,
    "Id": number,
    "AbilityLine": number,
    "Priority": number,
    "HideInUi": false,
    "Faction": number,
    "DurationSteps": number,
    "FinishingSpellId": number,
    "Icon": string,
    "BuffCategory": number,
    "Previews": number[],
    "ParametersContainer": {
        "Version": number,
        "Parameters": {
            "Id": number,
            "Value": number,
            "Type": number,
        }[],
    },
    "EffectsContainer": {
        "Version": number,
        "Effects": number[],
    },
}

export enum AbilityParameterIds {
    GenericCavalrySpeed = 3,
    DelaySteps = 12,
    Damage = 13,
    DamageOnSingleStructure2 = 349,
    Radius = 360,
    DamageOnSingleUnit = 362,
    BonusDmgAgainst = 363,
    TotalCombinedDamage = 364,
    AbilityOnTarget = 374,
    AbilityOnTarge2 = 375,
    TargetableLayers = 414,
    TotalDamage = 422,
    WeaponType = 423,
    DamagePerTarget = 424,
    TargetableEntityTypes = 425,
    DamageOnSingleStructure = 437,
    Interval = 755,
    TotalDamagePerInterval = 756,
}