export interface Building {
    "Version": number,
    "Id": number,
    "CardId": number,
    "Health": number,
    "ArmorType": number,
    "AngleOffset": number,
    "HealthBarSize": number,
    "SelectionRadius": number,
    "Flags": number,
    "DBFolderId": number,
    "Status": number,
    "ProductionPower": number,
    "ProductionTime": number,
    "ThreatValue": number,
    "VisLookAtInterest": number,
    "UiPreviewRadius": number,
    "Scaling": number,
    "IconImage": {
        "Icon": string,
        "Artwork": string,
    },
    "AmmoTypeDisplay": number,
    "ModeIds": number[],
    "PvETypeIds": number[],
    "MeshContainer": {
        "Version": number,
        "Meshes": {
            "Id": number,
            "Type": number,
            "FilePath": string,
        }[],
    },
    "Classes": number[],
}